image: openjdk:8

variables:
  GIT_STRATEGY: clone
  SSL_SELF_SIGNED: "true"
  PROJECTNAME: "KeysPerSecond"

before_script:
  - java -version

stages:
  - compile
  - status
  - javadoc

pending:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} pending
  stage: compile

success:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} success
  when: on_success
  stage: status

failure:
  allow_failure: true
  script:
    - curl ${SERVER}ci/status.sh | bash -s ${PROJECTNAME} ${CI_COMMIT_SHA} failure
  when: on_failure
  stage: status

verify:
  allow_failure: true
  script:
    - wget ${SERVER}ci/javadoc.sh
    - chmod 755 javadoc.sh
    - ./javadoc.sh
  stage: javadoc

javadoc:
  script:
    - mkdir ../javadoc
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} javadoc
    - mv ./build/docs/javadoc/* ../javadoc
  stage: javadoc
  environment: javadoc
  artifacts:
    name: "$PROJECTNAME"
    expire_in: 1 week
    paths:
      - javadoc/

compile:
  script:
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} shadowJar
    - ./gradlew -PnexusPublic=${NEXUS_PUBLIC} createExe
    - mv ./build/libs/* ../
    - mv ./build/launch4j/*.exe ../
  stage: compile
  environment: builds
  artifacts:
    name: "${PROJECTNAME}"
    expire_in: 1 week
    paths:
      - ${PROJECTNAME}-*.jar
      - ${PROJECTNAME}-*.exe
